### ISSUE TITLE
current time for a timezone

### ISSUE THREAD

**Issue by loklaan** [lampewebdev/elementarybot#2]
as a person in a australia, i want to know the current time in places that i know elementary devs are located, so i can hassle them at when they're least tired

I made up the last bit, but you get the gist. It'd be cool.

**!time <city, land>**
or
**!time <est>** _(abbreviated standard times)_
or
**!time <-3>** / **!time <+10>** _(yeah, not too helpful)_

**Comment by lampe** [comment]
hey

i will look into it.
never worked with the ruby time class so much but i will look into it 
maybe there is a service that can do that? that returns a xml or json ?

**Comment by loklaan** [comment]
rbot has a time & timezone plugin. rbot is gpl v2

you could look into that if you wish :)

**Comment by lampe** [comment]
i looked into that source code: 
they use tzinfo i could use that too ;)
I could use some parts of there code :P
or get "inspiration" by there code ;)
source:
http://ruby-rbot.org/rbot-trac/browser/data/rbot/plugins/time.rb?rev=edd1cf77be07ae507014574141e920ad23eb164d

**Comment by loklaan** [comment]
MIT license. You're fine. :)

**Comment by loklaan** [comment]
Cleaning up my dead issues. Cheers.
