### ISSUE TITLE
Idea: !ot <name>

### ISSUE THREAD

**Issue by PhillipSz** [lampewebdev/elementarybot#3]
»ot« stands for offtopic and it would tell the user to go to #elementary-offtopic. Because #elementary is a support channel and if users dont talk about elementary this command would be usefull.

**Comment by lampe** [comment]
this should be easy to implement!
i will look into it next week when i'm back from a short trip ;)

**Comment by PhillipSz** [comment]
okey thanks a lot ;)

**Comment by lampe** [comment]
implemented 
when i restart the bot it will be there !

**Comment by PhillipSz** [comment]
Thanks!Danke! ;)
