### ISSUE TITLE
!nick <nick> to change its nick

### ISSUE THREAD

**Issue by voldyman** [lampewebdev/elementarybot#4]
due to disconnects there are a lot of '_' post-fixed to the nice of minion bot !nick will help the authenticated user fix that.

**Comment by lampe** [comment]
i dont understand it :D

**Comment by voldyman** [comment]
Currently the not has the nick MinionBot____ 
A OP should be able to do !nick  and the not changes its nick to MinionBot, removing the '_'

**Comment by lampe** [comment]
okay :D thats what i thought 
then it is only !nick
without <nick> ;)
